# Generated by Django 4.2.2 on 2023-06-07 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Canasta', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Contenido_Total', models.FloatField(default=0.0)),
                ('Azucar', models.FloatField(default=0.0)),
                ('Limon', models.FloatField(default=0.0)),
                ('Producto_no_Conforme', models.FloatField(default=0.0)),
                ('Fruta_Seleccionada', models.FloatField(default=0.0)),
                ('Inicio_Jornada', models.TimeField()),
                ('Seleccion_del_Producto', models.TimeField()),
                ('Fresa_Entra_a_la_Olla', models.TimeField()),
                ('Hervor_Inicio', models.TimeField()),
                ('Introduccion_Azucar', models.TimeField()),
                ('Introduccion_Limon', models.TimeField()),
                ('Hervor_Final', models.TimeField()),
                ('Hora_Licuado', models.TimeField()),
                ('Hora_Final_Fresa', models.TimeField()),
                ('Inicio_de_Empaque', models.TimeField()),
                ('Finalizacion_de_la_Canasta', models.TimeField()),
                ('Valor_Primer_Brix', models.FloatField(default=0.0)),
                ('Hora_Primer_Brix', models.TimeField()),
                ('Valor_Brix_Final', models.FloatField(default=0.0)),
                ('Hora_Brix_Final', models.TimeField()),
                ('Producto_Terminado', models.IntegerField(default=0)),
                ('Media_Libra', models.IntegerField(default=0)),
                ('Libra', models.IntegerField(default=0)),
                ('Bolsa_Seis_kg', models.IntegerField(default=0)),
                ('Otro', models.IntegerField(default=0, null=True)),
                ('Observaciones', models.CharField(max_length=200, null=True)),
                ('Usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Canasta', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Contenido_Total', models.FloatField(default=0.0)),
                ('Azucar', models.FloatField(default=0.0)),
                ('Sorbato', models.FloatField(default=0.0)),
                ('Producto_no_Conforme', models.FloatField(default=0.0)),
                ('Fruta_Seleccionada', models.FloatField(default=0.0)),
                ('Inicio_Jornada', models.TimeField()),
                ('Seleccion_del_Producto', models.TimeField()),
                ('Mora_Entra_a_la_Olla', models.TimeField()),
                ('Hervor_Inicio', models.TimeField()),
                ('Hervor_Final', models.TimeField()),
                ('Enfriamiento_Inicio', models.TimeField()),
                ('Enfriamiento_Final', models.TimeField()),
                ('Inicio_Despulpado', models.TimeField()),
                ('Final_Despulpado', models.TimeField()),
                ('Segunda_Coccion', models.TimeField()),
                ('Hora_Final_Mora', models.TimeField()),
                ('Inicio_de_Empaque', models.TimeField()),
                ('Finalizacion_de_la_Canasta', models.TimeField()),
                ('Semilla', models.FloatField(default=0.0)),
                ('Pulpa', models.FloatField(default=0.0)),
                ('Valor_Primer_Brix', models.FloatField(default=0.0)),
                ('Hora_Primer_Brix', models.TimeField()),
                ('Valor_Brix_Final', models.FloatField(default=0.0)),
                ('Hora_Brix_Final', models.TimeField()),
                ('Producto_Terminado', models.IntegerField(default=0)),
                ('Media_Libra', models.IntegerField(default=0)),
                ('Libra', models.IntegerField(default=0)),
                ('Bolsa_Seis_kg', models.IntegerField(default=0)),
                ('Otro', models.IntegerField(default=0, null=True)),
                ('Observaciones', models.CharField(max_length=200, null=True)),
                ('Usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
